- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline.xml') }}"
    name: "test"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
    token: "115f9fa66f82cfd6885ba1916e6395514a"
  loop:
    - { repoName: "cart", componentName: "cart" }