- name: Create a jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.name}}"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
    token: "115f9fa66f82cfd6885ba1916e6395514a"
  loop:
    - { name: "CI-Pipelines", description: "CI pipelines for roboshop components" }



- name: Create a jenkins single pipeline
  community.general.jenkins_job:
    config: "{{ lookup('template', 'pipeline.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
    token: "115f9fa66f82cfd6885ba1916e6395514a"
  loop:
    - { jobName: "cart", folderName: "CI-Pipelines/", repoName: "cart", componentName: "cart" }